# Generated by Django 4.0.5 on 2022-06-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subjects',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
