# Generated by Django 4.0.5 on 2022-06-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image_profile_position_profile_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
